### ISSUE TITLE
QT no Makefile found? is it normal?

### ISSUE THREAD

**Issue by eliodilar** [jserot/caph#4]
![qtmakefile](https://user-images.githubusercontent.com/44893881/48338298-93c44900-e665-11e8-89ed-934c86c192e8.png)

Héllo,

After have commented Doc builder compiler and sed -E parameter cmd remove i have a new problem.
Is it normal that there is no makefile in the GUI folder?

Cordially

**Comment by eliodilar** [comment]
path QMAKE not defined
CAPH DATA FLOW turn on QT4.

Install QT5 not possible because QT4 declared in hard in code i think.
Attention, if you install QT5 after QT4 , Mkspecs QT4 is replace by QT5 %PATH declaration not possible.

I try to declarde PATH for Caph- Qt mkspecs gui

**Comment by jserot** [comment]
The `Makefile` has to be built from the `.pro` file according to your local Qt installation using `qmake`. 

For example, on my MacOS platform (10.9, Qt 5.2.1), the command for building it is :

`qmake -spec macx-clang -o Makefile caph.pro`

**Comment by eliodilar** [comment]
compiled directly on QT
