### ISSUE TITLE
.dot generate error

### ISSUE THREAD

**Issue by eliodilar** [jserot/caph#5]
If you have an idea.

Dotty Path is ok. But .dot generation is not ok.
what is the version of grahviz or dotty who you use?

cordially 
![caph](https://user-images.githubusercontent.com/44893881/48427605-6b257780-e769-11e8-9678-61c791424657.png)

**Comment by eliodilar** [comment]
stand by can be cause by coding error

**Comment by jserot** [comment]
Check that you can run `dotty` from the command line (i.e. type `/usr/bin/dotty` from a terminal).

**Comment by eliodilar** [comment]
I have also try, its make me a problem to load file


![dotty](https://user-images.githubusercontent.com/44893881/48470202-1594ad80-e7f1-11e8-8fa6-7439aef5aef2.png)

**Comment by eliodilar** [comment]
that's what i have, look in the graph there is no scale, inp, like in your example.
What is the lib who generate that DotViewer also?

![dot](https://user-images.githubusercontent.com/44893881/48471489-475b4380-e7f4-11e8-8ef2-815a413664b0.png)

**Comment by eliodilar** [comment]
ok, its strange with dotty i have problem but with dot viewer no problem 
![dotviewer](https://user-images.githubusercontent.com/44893881/48473432-bc307c80-e7f8-11e8-8af9-a54fc5964ac6.png)

**Comment by eliodilar** [comment]
# Warning: node n1, port s0 unrecognized
# Warning: node n2, port e0 unrecognized

**Comment by eliodilar** [comment]
resolve with kgrap

**Comment by jserot** [comment]
Seems that the `dotty` command included in the `Graphviz` package for Linux is outdated and does not support some features of the `.dot` language :(

The workaround is use the `dot` command for viewing graphs.

This may be done by defining, for instance, a command `dotv` as the following bash script :

```
#!/bin/bash
dot -Tpng $1 | xloadimage stdin
```

and specify `dotv` (or `<path>/dotv` is `path` is not your in your`$PATH`) as the dot viewer in the Caph configuration section.

**Comment by eliodilar** [comment]
caph dot viewer configuration path: /usr/bin/dotv

dotv bash name ( dotv):
#!/bin/bash
dot -Tpng $1 | xloadimage stdin

no result, do you know a strongest dot viewwer?

have a good day 

![dotv](https://user-images.githubusercontent.com/44893881/48496552-8c05cf80-e832-11e8-9532-9311ae68da0e.png)

**Comment by jserot** [comment]
Check that 
- `/usr/bin/dotv` is executable (`chmod a+x /usr/bin/dotv`)
- `xloadimage` is installed on your machine

**Comment by eliodilar** [comment]
![vvv](https://user-images.githubusercontent.com/44893881/48498370-6ed30000-e836-11e8-9fc1-b86a0fa5d6f5.png)

**Comment by jserot** [comment]
Ah yes. `xdot` is a good - and simpler - alternative.

**Comment by jserot** [comment]
Is it working now with `xdot` ? 
If yes, may i close the issue ?
